---
title: "part2"
output: html_document
date: "2026-06-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
setwd("/Users/marco/Desktop/epigenHypoxia/")
```

## Differential Accessibility Analysis with edgeR
```{r}
library(edgeR)

count_matrix <- readRDS("peaks/atac_count_matrix.rds")
cat("Total consensus peaks:", nrow(count_matrix), "\n")

# Define groups based on the column names of atac_count_matrix that are: Ctlr_N_1, Ctlr_N_2, Ctlr_H_1, Ctlr_H_2, CC_N_1, CC_N_2, CC_H_1, CC_H_2
groups <- factor(c("Ctlr_N", "Ctlr_N", "Ctlr_H", "Ctlr_H", "CC_N", "CC_N", "CC_H", "CC_H"))

# Initialize edgeR object, filter background noise, and normalize
y <- DGEList(counts = count_matrix, group = groups)
y <- calcNormFactors(y)

# Set up the statistical design
design <- model.matrix(~0 + groups)
colnames(design) <- levels(groups)

# Estimate variance (dispersion) and fit the model
y <- estimateDisp(y, design)
fit <- glmQLFit(y, design) # Quasi-Likelihood Negative Binomial

# Define your exact 2x2 experimental questions
my_contrasts <- makeContrasts(   
  Ctlr_H_vs_Ctrl_N = Ctlr_H - Ctlr_N, # Baseline hypoxia response -> log2(Ctlr_H) - log2(Ctlr_N) = log2(Ctlr_H/Ctlr_N) = log2FC
  CC_N_vs_Ctlr_N  = CC_N - Ctlr_N,   # Baseline co-culture response
  CC_H_vs_CC_N   = CC_H - CC_N,     # Hypoxia effect during co-culture
  CC_H_vs_Ctrl_H   = CC_H - Ctlr_H,   # Co-culture effect during hypoxia
  levels = design
)

# Run the tests for all 4 contrasts
test1 <- glmQLFTest(fit, contrast=my_contrasts[,"Ctlr_H_vs_Ctrl_N"])
test2 <- glmQLFTest(fit, contrast=my_contrasts[,"CC_N_vs_Ctlr_N"])
test3 <- glmQLFTest(fit, contrast=my_contrasts[,"CC_H_vs_CC_N"])
test4 <- glmQLFTest(fit, contrast=my_contrasts[,"CC_H_vs_Ctrl_H"])

# Extract the significant tables for each
diff_Ctlr_H_vs_Ctrl_N <- topTags(test1, n=Inf, p.value=0.05)$table
diff_CC_N_vs_Ctlr_N <- topTags(test2, n=Inf, p.value=0.05)$table
diff_CC_H_vs_CC_N <- topTags(test3, n=Inf, p.value=0.05)$table
diff_CC_H_vs_Ctrl_H <- topTags(test4, n=Inf, p.value=0.05)$table

cat("Significant DA peaks in Ctlr_H_vs_Ctrl_N:", nrow(diff_Ctlr_H_vs_Ctrl_N), "\n")
cat("Significant DA peaks in CC_N_vs_Ctlr_N:", nrow(diff_CC_N_vs_Ctlr_N), "\n")
cat("Significant DA peaks in CC_H_vs_CC_N:", nrow(diff_CC_H_vs_CC_N), "\n")
cat("Significant DA peaks in CC_H_vs_Ctrl_H:", nrow(diff_CC_H_vs_Ctrl_H), "\n")

#head(diff_Ctlr_H_vs_Ctrl_N)
```

## Volcano Plot
```{r}
library(ggplot2)

plot_volcano <- function(df, plot_title) {
  # Categorize each peak
  df$Significance <- "Not Significant"
  df$Significance[df$FDR < 0.05 & df$logFC > 0.6] <- "Up"
  df$Significance[df$FDR < 0.05 & df$logFC < -0.6] <- "Down"
  
  # Plotting volcano
  p <- ggplot(df, aes(x = logFC, y = -log10(FDR), color = Significance)) +
    geom_point(alpha = 0.6, size = 1.2) +
    scale_color_manual(values = c("Down" = "blue", "Not Significant" = "gray", "Up" = "red")) +
    theme_minimal() +
    labs(title = plot_title, x = "Log2 Fold Change", y = "-Log10 FDR") +
    geom_vline(xintercept = c(-0.6, 0.6), linetype = "dashed") +
    geom_hline(yintercept = -log10(0.05), linetype = "dashed")
  
  print(p)
  return(df)
}

diff_Ctlr_H_vs_Ctrl_N <- plot_volcano(diff_Ctlr_H_vs_Ctrl_N, "Hypoxia vs Normoxia in monoculture")
diff_CC_H_vs_CC_N <- plot_volcano(diff_CC_H_vs_CC_N, "Hypoxia vs Normoxia in co-culture")
diff_CC_N_vs_Ctlr_N <- plot_volcano(diff_CC_N_vs_Ctlr_N, "Co vs monocolture in Normoxia")
diff_CC_H_vs_Ctrl_H <- plot_volcano(diff_CC_H_vs_Ctrl_H, "Co vs monocolture in Hypoxia")

```

## Genomic Annotation Distribution Across Conditions
```{r}
library(GenomicRanges)
library(ChIPseeker)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(org.Mm.eg.db)
library(limma)

txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
consensus_peaks <- readRDS("peaks/ATAC_consensus.rds")
get_granges_dir <- function(diff_table, consensus, direction) {
  
  if (direction == "up") {
    sig_peaks <- rownames(diff_table)[diff_table$logFC > 0.6 & diff_table$FDR < 0.05]
  } else {
    sig_peaks <- rownames(diff_table)[diff_table$logFC < -0.6 & diff_table$FDR < 0.05]
  }
  
  # Map back to GRanges object
  if ("name" %in% colnames(mcols(consensus))) {
    return(consensus[consensus$name %in% sig_peaks])
  } else {
    return(consensus[names(consensus) %in% sig_peaks])
  }
}

gr_list <- list(
  CC_Up      = get_granges_dir(diff_CC_N_vs_Ctlr_N, consensus_peaks, "up"),
  CC_Down    = get_granges_dir(diff_CC_N_vs_Ctlr_N, consensus_peaks, "down"),
  CC_Hyp_Up  = get_granges_dir(diff_CC_H_vs_CC_N, consensus_peaks, "up"),
  CC_Hyp_Down= get_granges_dir(diff_CC_H_vs_CC_N, consensus_peaks, "down"),
  Hyp_Up     = get_granges_dir(diff_Ctlr_H_vs_Ctrl_N, consensus_peaks, "up"),
  Hyp_Down   = get_granges_dir(diff_Ctlr_H_vs_Ctrl_N, consensus_peaks, "down")
)

invisible(capture.output(anno_list <- lapply(gr_list, annotatePeak, tssRegion=c(-2000, 2000), TxDb=txdb, annoDb="org.Mm.eg.db")))
plotAnnoBar(anno_list, title="Genomic Annotation Distribution (Up vs Down)")
```

## Veen Diagram (genic regions)
```{r}
# Annotate ALL consensus peaks first
anno_all <- annotatePeak(consensus_peaks, tssRegion=c(-2000, 2000), TxDb=txdb, annoDb="org.Mm.eg.db")
df_anno <- as.data.frame(anno_all)

# Extract IDs for peaks located at Promoters, Introns, or Exons
peak_ids <- if("name" %in% colnames(df_anno)) df_anno$name else rownames(df_anno)
gene_body_ids <- peak_ids[grepl("Promoter|Intron|Exon", df_anno$annotation)]
correct_gene_body_ids <- paste0("ATAC_IDR_peak_", gene_body_ids)

res_CC    <- decideTests(test2[rownames(test2) %in% correct_gene_body_ids, ], p.value = 0.05, lfc = 0.6)
res_Hyp   <- decideTests(test1[rownames(test1) %in% correct_gene_body_ids, ], p.value = 0.05, lfc = 0.6)
res_CCHyp <- decideTests(test3[rownames(test3) %in% correct_gene_body_ids, ], p.value = 0.05, lfc = 0.6)

results_3way <- cbind(CC  = res_CC, Hyp = res_Hyp, CC_Hyp = res_CCHyp )
colnames(results_3way) <- c("Co-Culture", "Hypoxia", "Co-Culture+Hypoxia")

#Venn Diagram
par(mar = c(4, 4, 8, 4), cex = 0.7)
vennDiagram(results_3way, include = c("up", "down"), counts.col = c("blue", "red"),
            main = "Gene Body Peaks", cex.main = 2.0)
```

## Extract "synergy" genes from only Co-Culture+Hypoxia
```{r}
up_peaks <- rownames(results_3way)[
  results_3way[,"Co-Culture+Hypoxia"] == 1 & 
  results_3way[,"Co-Culture"] != 1 & 
  results_3way[,"Hypoxia"] != 1
]
down_peaks <- rownames(results_3way)[
  results_3way[,"Co-Culture+Hypoxia"] == -1 & 
  results_3way[,"Co-Culture"] != -1 & 
  results_3way[,"Hypoxia"] != -1
]
up_raw_ids <- gsub("ATAC_IDR_peak_", "", up_peaks)
down_raw_ids <- gsub("ATAC_IDR_peak_", "", down_peaks)

genes_up <- unique(na.omit(df_anno$SYMBOL[rownames(df_anno) %in% up_raw_ids]))
genes_down <- unique(na.omit(df_anno$SYMBOL[rownames(df_anno) %in% down_raw_ids]))

cat("Unique UP peaks:", length(up_peaks), "of unique UP genes:",length(genes_up),"\n")
cat("Unique DOWN peaks:", length(down_peaks), "of unique DOWN genes",length(genes_down),"\n" )
```

### rGREAT enrichement analysis
```{r fig.width=10, fig.height=8}
library(rGREAT)
library(dplyr)

gr_up   <- consensus_peaks[as.numeric(up_raw_ids)]
gr_down <- consensus_peaks[as.numeric(down_raw_ids)]

# Run GREAT analysis (Background = entire ATAC-seq universe)
res_up_BP   <- great(gr_up,   gene_sets="GO:BP", tss_source="mm10", background=consensus_peaks, cores=4)
res_down_BP <- great(gr_down, gene_sets="GO:BP", tss_source="mm10", background=consensus_peaks, cores=4)
res_up_CC   <- great(gr_up,   gene_sets="GO:CC", tss_source="mm10", background=consensus_peaks, cores=4)
res_down_CC <- great(gr_down, gene_sets="GO:CC", tss_source="mm10", background=consensus_peaks, cores=4)
res_up_MF   <- great(gr_up,   gene_sets="GO:MF", tss_source="mm10", background=consensus_peaks, cores=4)
res_down_MF <- great(gr_down, gene_sets="GO:MF", tss_source="mm10", background=consensus_peaks, cores=4)

bp_up <- bind_rows(
  "GO:BP" = getEnrichmentTables(res_up_BP),
# "GO:CC" = getEnrichmentTables(res_up_CC), # choose which Ont to add
  "GO:MF" = getEnrichmentTables(res_up_MF),
  .id = "Ontology"
) %>% filter(p_adjust < 0.05) %>%
  arrange(desc(p_adjust)) %>% #sort by FoldChange: arrange(desc(fold_enrichment)) or by p_adj: arrange(desc(p_adjust))
  mutate(description = factor(description, levels = unique(description)))

bp_down <- bind_rows(
  "GO:BP" = getEnrichmentTables(res_down_BP),
  "GO:CC" = getEnrichmentTables(res_down_CC),
  "GO:MF" = getEnrichmentTables(res_down_MF),
  .id = "Ontology"
) %>% filter(p_adjust < 0.05) %>%
  arrange(desc(p_adjust)) %>% 
  mutate(description = factor(description, levels = unique(description)))

ggplot(head(bp_up, 15), aes(x = fold_enrichment, 
  y = description, size = observed_region_hits, color = -log10(p_adjust))) + 
  geom_point() + scale_color_viridis_c() + theme_minimal() +
  ggtitle("GREAT: Exclusively Opened Regions (UP)")

ggplot(head(bp_down, 15), aes(x = fold_enrichment, 
  y = description, size = observed_region_hits, color = -log10(p_adjust))) + 
  geom_point() + scale_color_viridis_c() + theme_minimal() +
  ggtitle("GREAT: Exclusively Closed Regions (DOWN)")
```

